import { PERFECT_NETWORK, type NetworkConditions } from '@ah/protocol';

import type { LinkMode } from './link.js';
import { runScenario, type ScenarioConfig, type ScenarioResult } from './scenario.js';

/**
 * Measurement CLI.
 *
 * Prints markdown tables that go straight into the README. Engineers discount
 * adjectives and trust measured claims, so the project's assertions about
 * smoothness should all be traceable to a command anyone can re-run.
 *
 *   npm run measure -w @ah/harness
 *   npm run measure -w @ah/harness -- --seconds 60 --seed 7
 */

const args = process.argv.slice(2);

function flag(name: string, fallback: number): number {
  const index = args.indexOf(`--${name}`);
  if (index === -1) return fallback;
  const value = Number(args[index + 1]);
  return Number.isFinite(value) ? value : fallback;
}

const SECONDS = flag('seconds', 30);
const SEED = flag('seed', 20260816);

function conditions(rttMs: number, jitterMs = 0, lossRate = 0): NetworkConditions {
  return { ...PERFECT_NETWORK, rttMs, jitterMs, lossRate };
}

function u(n: number): string {
  return n.toFixed(1);
}

function ms(n: number): string {
  return n.toFixed(0);
}

function kib(n: number): string {
  return (n / 1024).toFixed(2);
}

function run(config: ScenarioConfig): ScenarioResult {
  process.stderr.write(`  running ${config.label}...\n`);
  return runScenario(config);
}

const base = { seconds: SECONDS, seed: SEED, mode: 'reliable-ordered' as LinkMode };

// ---------------------------------------------------------------------------
// 1. What netcode is worth, as latency rises
// ---------------------------------------------------------------------------

const LATENCIES = [0, 50, 100, 200, 300];

const onOff: Array<{ rtt: number; on: ScenarioResult; off: ScenarioResult }> = [];
for (const rtt of LATENCIES) {
  onOff.push({
    rtt,
    on: run({ ...base, label: `netcode on, ${rtt}ms`, conditions: conditions(rtt), netcode: true }),
    off: run({ ...base, label: `netcode off, ${rtt}ms`, conditions: conditions(rtt), netcode: false }),
  });
}

// ---------------------------------------------------------------------------
// 2. Behaviour under genuinely hostile conditions
// ---------------------------------------------------------------------------

const HOSTILE: Array<[string, NetworkConditions]> = [
  ['clean 100ms', conditions(100)],
  ['100ms + 30ms jitter', conditions(100, 30)],
  ['100ms + 2% loss', conditions(100, 0, 0.02)],
  ['200ms + 50ms jitter + 5% loss', conditions(200, 50, 0.05)],
  ['300ms + 80ms jitter + 10% loss', conditions(300, 80, 0.1)],
];

const hostile = HOSTILE.map(([label, c]) =>
  run({ ...base, label, conditions: c, netcode: true }),
);

// ---------------------------------------------------------------------------
// 3. What TCP costs, measured
// ---------------------------------------------------------------------------

const transport: Array<{ label: string; unreliable: ScenarioResult; reliable: ScenarioResult }> = [];
for (const loss of [0.01, 0.05, 0.1]) {
  const c = conditions(100, 20, loss);
  transport.push({
    label: `${(loss * 100).toFixed(0)}% loss`,
    unreliable: run({
      ...base,
      mode: 'unreliable',
      label: `datagram, ${loss * 100}% loss`,
      conditions: c,
      netcode: true,
    }),
    reliable: run({
      ...base,
      mode: 'reliable-ordered',
      label: `tcp-like, ${loss * 100}% loss`,
      conditions: c,
      netcode: true,
    }),
  });
}

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

const out: string[] = [];

out.push(`<!-- generated by: npm run measure -w @ah/harness -- --seconds ${SECONDS} --seed ${SEED} -->`);
out.push('');
out.push(`_${SECONDS}s per scenario, seed ${SEED}, two simulated players, WebSocket (TCP) semantics unless stated._`);
out.push('');

out.push('### What the netcode is worth');
out.push('');
out.push('On-screen paddle position versus a zero-latency local game, in rink units.');
out.push('The rink is 1000 x 600, and a paddle is 34 units across.');
out.push('');
out.push('| RTT | netcode off (p50) | netcode off (p99) | **netcode on (p50)** | **netcode on (p99)** |');
out.push('|---:|---:|---:|---:|---:|');
for (const row of onOff) {
  out.push(
    `| ${row.rtt} ms | ${u(row.off.paddleLagUnits.p50)} | ${u(row.off.paddleLagUnits.p99)} ` +
      `| **${u(row.on.paddleLagUnits.p50)}** | **${u(row.on.paddleLagUnits.p99)}** |`,
  );
}
out.push('');

out.push('### Holding up under impairment');
out.push('');
out.push('Reconciliation disagreement is zero whenever the server saw every input;');
out.push('it becomes non-zero only when inputs are lost or arrive too late to use.');
out.push('');
out.push('| Conditions | correction p50 | correction p99 | corrections/s | starved frames | goals |');
out.push('|---|---:|---:|---:|---:|---:|');
for (const r of hostile) {
  out.push(
    `| ${r.label} | ${u(r.correction.p50)} | ${u(r.correction.p99)} ` +
      `| ${r.correctionsPerSecond.toFixed(1)} | ${(r.starvedFrameRatio * 100).toFixed(2)}% | ${r.goals} |`,
  );
}
out.push('');

out.push('### What TCP costs');
out.push('');
out.push('Observed one-way delivery latency. The reliable column is the transport this');
out.push('project actually ships on: a lost packet is retransmitted rather than dropped,');
out.push('and everything behind it waits — head-of-line blocking.');
out.push('');
out.push('| Loss | datagram p50 | datagram p99 | TCP-like p50 | **TCP-like p99** | retransmits |');
out.push('|---|---:|---:|---:|---:|---:|');
for (const row of transport) {
  out.push(
    `| ${row.label} | ${ms(row.unreliable.deliveryToClientMs.p50)} ms | ${ms(row.unreliable.deliveryToClientMs.p99)} ms ` +
      `| ${ms(row.reliable.deliveryToClientMs.p50)} ms | **${ms(row.reliable.deliveryToClientMs.p99)} ms** ` +
      `| ${row.reliable.retransmits} |`,
  );
}
out.push('');

// ---------------------------------------------------------------------------
// 5. Lag compensation
// ---------------------------------------------------------------------------

const compRows = [50, 150, 300].map((rtt) => ({
  rtt,
  on: run({ ...base, label: `rewind on, ${rtt}ms`, conditions: conditions(rtt, 30), netcode: true }),
  off: run({
    ...base,
    label: `rewind off, ${rtt}ms`,
    conditions: conditions(rtt, 30),
    netcode: true,
    rewindWindowTicks: 0,
  }),
}));

out.push('### Lag compensation');
out.push('');
out.push('Inputs carry the tick the client simulated them at, and the server applies');
out.push('each one there — rewinding and replaying when it arrives after that tick has');
out.push('already been simulated. Without it a strike that plainly connected on the');
out.push('player’s screen lands in the right place at the wrong moment, and misses.');
out.push('');
out.push('Note what the correction columns do *not* say. Rewinding does not reduce');
out.push('reconciliation corrections — it slightly increases them, because revising the');
out.push('server’s past means a client that already reconciled against the pre-revision');
out.push('snapshot has to be nudged again. The benefit is not fewer corrections; it is');
out.push('that the input lands at the tick it was meant for, so the strike connects.');
out.push('That property is asserted directly in `packages/server/test/rewind.test.ts`,');
out.push('which checks a late input produces the same state as one that was never late.');
out.push('');
out.push('| RTT (+30ms jitter) | late inputs/s | rewinds/s | avg rewind depth | correction p99, rewind **on** | correction p99, rewind **off** |');
out.push('|---:|---:|---:|---:|---:|---:|');
for (const row of compRows) {
  out.push(
    `| ${row.rtt} ms | ${row.on.lateInputsPerSecond.toFixed(1)} | ${row.on.rewindsPerSecond.toFixed(1)} ` +
      `| ${row.on.averageRewindTicks.toFixed(1)} ` +
      `| **${u(row.on.correction.p99)}** | ${u(row.off.correction.p99)} |`,
  );
}
out.push('');
out.push('Client lead, in ticks, and how often the server reported an empty forward');
out.push('buffer — the signal the client steers on:');
out.push('');
out.push('| RTT | lead p50 | starved reports/s | discarded (beyond window)/s |');
out.push('|---:|---:|---:|---:|');
for (const row of compRows) {
  out.push(
    `| ${row.rtt} ms | ${row.on.leadTicks.p50.toFixed(0)} ` +
      `| ${row.on.starvedReportsPerSecond.toFixed(1)} | ${row.on.tooLatePerSecond.toFixed(2)} |`,
  );
}
out.push('');

// ---------------------------------------------------------------------------
// 6. Wire format
// ---------------------------------------------------------------------------

const codecRows = [
  { label: 'clean 100ms', c: conditions(100) },
  { label: '200ms + 50ms jitter', c: conditions(200, 50) },
].map((row) => ({
  label: row.label,
  json: run({ ...base, label: `json, ${row.label}`, conditions: row.c, netcode: true, codec: 'json' }),
  binary: run({
    ...base,
    label: `binary, ${row.label}`,
    conditions: row.c,
    netcode: true,
    codec: 'binary',
  }),
}));

out.push('### Wire format');
out.push('');
out.push('Three separate savings: no field names, 16-bit fixed-point instead of');
out.push('`float64`, and a bitmask naming only the field groups that changed since the');
out.push('previous snapshot. Delta encoding needs no keyframe recovery protocol here');
out.push('because the transport is TCP — the same reliability that causes head-of-line');
out.push('blocking guarantees no snapshot is ever missing.');
out.push('');
out.push('| Conditions | JSON down | **binary down** | JSON up | **binary up** | reduction |');
out.push('|---|---:|---:|---:|---:|---:|');
for (const row of codecRows) {
  const down = 1 - row.binary.bytesDownPerSecond / row.json.bytesDownPerSecond;
  out.push(
    `| ${row.label} | ${kib(row.json.bytesDownPerSecond)} KiB/s | **${kib(row.binary.bytesDownPerSecond)} KiB/s** ` +
      `| ${kib(row.json.bytesUpPerSecond)} KiB/s | **${kib(row.binary.bytesUpPerSecond)} KiB/s** ` +
      `| ${(down * 100).toFixed(0)}% |`,
  );
}
out.push('');
out.push('What it costs: quantisation gives up bit-exact state reconstruction. A client');
out.push('adopting a JSON snapshot resumes from the server’s exact numbers; one adopting');
out.push('a quantised snapshot resumes from rounded ones, so replay can no longer be');
out.push('bit-identical. The rounding step is ~0.018 units against a 0.05 correction');
out.push('dead zone, and reconciliation re-syncs every 3 ticks, so it does not surface —');
out.push('but it is a real property traded away rather than a free win.');
out.push('');
out.push('| Conditions | codec | correction p50 | correction p99 | corrections/s |');
out.push('|---|---|---:|---:|---:|');
for (const row of codecRows) {
  out.push(
    `| ${row.label} | JSON | ${u(row.json.correction.p50)} | ${u(row.json.correction.p99)} | ${row.json.correctionsPerSecond.toFixed(2)} |`,
  );
  out.push(
    `| ${row.label} | binary | ${u(row.binary.correction.p50)} | ${u(row.binary.correction.p99)} | ${row.binary.correctionsPerSecond.toFixed(2)} |`,
  );
}
out.push('');

// ---------------------------------------------------------------------------
// 4. Puck strategies, head to head
// ---------------------------------------------------------------------------

const strategyRows: Array<{
  rtt: number;
  interpolate: ScenarioResult;
  predict: ScenarioResult;
  authority: ScenarioResult;
}> = [];
for (const rtt of [50, 100, 200, 300]) {
  const forStrategy = (puckStrategy: 'interpolate' | 'predict' | 'authority'): ScenarioResult =>
    run({
      ...base,
      label: `puck ${puckStrategy}, ${rtt}ms`,
      conditions: conditions(rtt),
      netcode: true,
      puckStrategy,
    });

  strategyRows.push({
    rtt,
    interpolate: forStrategy('interpolate'),
    predict: forStrategy('predict'),
    authority: forStrategy('authority'),
  });
}

out.push('### Puck strategies, head to head');
out.push('');
out.push('How wrong the displayed puck was about the moment it claimed to depict,');
out.push('in rink units. Recorded when the client draws tick T, resolved once the');
out.push('server reaches T. The puck is 18 units across.');
out.push('');
out.push('**A** is never wrong about the past — it shows real snapshot data. It is');
out.push('wrong about *now*, which is what the player is looking at. **B** is right');
out.push('about now until the opponent plays the puck, because their input has not');
out.push('arrived; the failure lands in the tail. **C** predicts only while this');
out.push('client owns the puck, taking B’s median and A’s tail.');
out.push('');
out.push('`jump/s` counts frames where the displayed puck moved further than it');
out.push('physically could — a visible teleport rather than motion. Accuracy alone');
out.push('cannot see this, and it is half of what "feels right" means: a puck that is');
out.push('consistently late still moves smoothly, while one that is usually exact but');
out.push('occasionally snaps sideways reads as broken.');
out.push('');
out.push('| RTT | A p50 | A p99 | A jump/s | B p50 | B p99 | B jump/s | **C p50** | **C p99** | **C jump/s** |');
out.push('|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|');
for (const row of strategyRows) {
  out.push(
    `| ${row.rtt} ms | ${u(row.interpolate.puckErrorUnits.p50)} | ${u(row.interpolate.puckErrorUnits.p99)} ` +
      `| ${row.interpolate.puckJumpsPerSecond.toFixed(1)} ` +
      `| ${u(row.predict.puckErrorUnits.p50)} | ${u(row.predict.puckErrorUnits.p99)} ` +
      `| ${row.predict.puckJumpsPerSecond.toFixed(1)} ` +
      `| **${u(row.authority.puckErrorUnits.p50)}** | **${u(row.authority.puckErrorUnits.p99)}** ` +
      `| **${row.authority.puckJumpsPerSecond.toFixed(1)}** |`,
  );
}
out.push('');
out.push('No strategy wins outright, which is the honest result. B is the most');
out.push('accurate and the least smooth; A is the smoothest and the least accurate;');
out.push('C sits between them on both. What C actually buys is *where* its accuracy');
out.push('goes:');
out.push('');
out.push('The aggregate understates C, because it averages over frames where the puck');
out.push('is at the far end and the player is watching rather than playing. Split by');
out.push('who held authority, C is doing exactly what it was built to do — B’s');
out.push('accuracy when you are about to hit the puck, A’s correctness when you are not:');
out.push('');
out.push('| RTT | C, while you own it (p50 / p99) | C, while you do not (p50 / p99) | owned | handoffs/s |');
out.push('|---:|---:|---:|---:|---:|');
for (const row of strategyRows) {
  const owned = row.authority.puckErrorWhileOwned;
  const not = row.authority.puckErrorWhileNotOwned;
  out.push(
    `| ${row.rtt} ms | **${u(owned.p50)} / ${u(owned.p99)}** | ${u(not.p50)} / ${u(not.p99)} ` +
      `| ${(row.authority.puckOwnedRatio * 100).toFixed(0)}% ` +
      `| ${row.authority.puckHandoffsPerSecond.toFixed(1)} |`,
  );
}
out.push('');

/** The adaptive interpolation delay's floor — see `netcode/interpolation.ts`. */
const INTERPOLATION_FLOOR_MS = 58;

out.push('### How stale the puck looks (strategy A)');
out.push('');
out.push('How far into the past the on-screen puck actually is, found by matching it');
out.push('against recorded authoritative positions. Expected value is the');
out.push('interpolation delay plus half the round trip — which is exactly the cost of');
out.push('never predicting the puck, and what strategies B and C will reduce. The');
out.push('delay is adaptive and settles near its floor on these links, so the');
out.push('expected column uses that floor rather than the fixed value it replaced.');
out.push('');
out.push('| RTT | expected | p50 | p95 | p99 |');
out.push('|---:|---:|---:|---:|---:|');
for (const row of onOff) {
  out.push(
    `| ${row.rtt} ms | ~${ms(INTERPOLATION_FLOOR_MS + row.rtt / 2)} ms | ${ms(row.on.puckDisplayLagMs.p50)} ms ` +
      `| ${ms(row.on.puckDisplayLagMs.p95)} ms | ${ms(row.on.puckDisplayLagMs.p99)} ms |`,
  );
}
out.push('');

process.stdout.write(out.join('\n'));
process.stdout.write('\n');
